name: Deploy main branch

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: false

permissions: {}

jobs:
  validate:
    permissions:
      contents: read
    uses: $/.github/workflows/validate.yaml

  ui-check:
    name: UI
    permissions:
      contents: read # 2026-09-23
    uses: ockendenjo/actions/.github/workflows/ui-lint.yml@b0484bc934491a439496a0c92e64820e9b5f7638 # zizmor: ignore[stale-action-refs,ref-version-mismatch]
    with:
      working_dir: ui

  build:
    permissions:
      contents: read
    uses: $/.github/workflows/build.yaml

  deploy:
    needs: [validate, ui-check, build]
    permissions:
      id-token: write # AWS OIDC
      contents: read
    uses: $/.github/workflows/deploy.yaml
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
    with:
      env: pro
