name: PR checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yaml

  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  build:
    name: Build
    uses: ./.github/workflows/build.yaml
