name: PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml

  test:
    uses: ./.github/workflows/test.yaml

  build:
    uses: ./.github/workflows/build.yaml
