name: Test

on:
  workflow_call:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Node modules
        working-directory: ui
        run: npm install

      - name: Check formatting
        working-directory: ui
        run: npx prettier --check .
